version: '3.8'

services:
  postgresql:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toto
      POSTGRES_DB: API_REST

  redis:  
    image: redis:5
    ports:
      - "6379:6379"

volumes:
  postgres_data:
